# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

Run the `initialise.py` module, then for each question you can query the
answer or an hint with `hint(n)` or `answer(n)` for `n` question number.

In [2]:
%run initialise.py

ModuleNotFoundError: No module named 'generators'

#### 1. Import the numpy package under the name `np` (★☆☆)

In [3]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

#### 3. Create a null vector of size 10 (★☆☆)

In [4]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 4. How to find the memory size of any array (★☆☆)

In [10]:
foo = np.zeros(10)
print(foo.size * foo.itemsize)
print(foo.nbytes)

80
80


#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [16]:
v = np.zeros(10)
v[5] = 1
v

array([0., 0., 0., 0., 0., 1., 0., 0., 0., 0.])

#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [12]:
np.arange(start=10, stop=50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [20]:
foo = np.arange(10, dtype=int)
print(foo[::-1])

[9 8 7 6 5 4 3 2 1 0]


#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [21]:
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [34]:
foo = np.array([1,2,0,0,4,0])
print(np.nonzero(foo)) # this is preferred
print(np.where(foo > 0))
print(np.where(foo))

(array([0, 1, 4]),)
(array([0, 1, 4]),)
(array([0, 1, 4]),)


#### 11. Create a 3x3 identity matrix (★☆☆)

In [38]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values (★☆☆)

In [41]:
np.random.rand(3, 3, 3)

array([[[0.70022291, 0.25813039, 0.07493071],
        [0.91942624, 0.76661486, 0.48801418],
        [0.31288116, 0.66684685, 0.77438302]],

       [[0.76510713, 0.75948128, 0.98263439],
        [0.33971603, 0.17413847, 0.23189725],
        [0.71195712, 0.26223979, 0.54226743]],

       [[0.30739861, 0.73688164, 0.15067368],
        [0.91977094, 0.61655897, 0.43710067],
        [0.87930102, 0.49740763, 0.55740803]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [46]:
foo = np.random.rand(100).reshape(10,10)
print(np.min(foo))
print(np.max(foo))

0.005819560223949138
0.9983713713194999


#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [48]:
foo = np.random.rand(30)
print(np.mean(foo))

0.5776715699560816


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [58]:
ary = np.ones((5,5), dtype=int)
ary[1:-1, 1:-1] = 0
print(ary)


[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [56]:
ary = np.array([[1, 2], [3,4], [5,6]])
np.pad(ary, 1, mode='constant', constant_values=(0,0))

array([[0, 0, 0, 0],
       [0, 1, 2, 0],
       [0, 3, 4, 0],
       [0, 5, 6, 0],
       [0, 0, 0, 0]])

#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [66]:
print(0 * np.nan) # expect: nan
print(np.nan == np.nan) # expect: false
print(np.inf > np.nan) # expect: false
print(np.nan - np.nan) # expect: nan
print(np.nan in set([np.nan])) # expect: false (actually true - because set membership works differently)
print(0.3 == 3 * 0.1) # expect: false

nan
False
False
nan
True
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [73]:
# First attempt
outer = np.zeros(25).reshape(5,5)
inner = np.diag([1,2,3,4])
outer[1:5,0:4] = inner

# Another way
a = np.zeros((5,5))
a += np.diag([1,2,3,4], k=-1)

# The actual solution
print(np.diag([1,2,3,4], k=-1))


[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [91]:
ind = np.indices((8,8))
a = ind[0] & 1
b = ind[1] & 1
#print(a)
#print(b)
c = a ^ b

(np.indices((8,8)) & 1).sum(axis=0) % 2

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

In [96]:
np.unravel_index(100, (6,7,8))

(1, 5, 4)

#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [97]:
np.tile(np.array([[1, 0], [0, 1]]), (4,4))

array([[1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1]])

#### 22. Normalize a 5x5 random matrix (★☆☆)

In [107]:
vals = np.random.rand(5,5)

# sum to 1
norm = vals / np.sum(vals)
print(norm.sum())

# scale to max 1
norm = vals / np.max(vals)
print(norm)

# scale to range [0,1]
norm = (vals - vals.min()) / (vals.max() - vals.min())
print(norm)

1.0
[[0.75285228 0.47738546 0.84298159 0.97257453 0.81064463]
 [0.95906707 0.04507842 0.83770119 0.52472666 0.00591097]
 [0.81234103 0.7501192  0.00412018 0.84705589 0.6350035 ]
 [0.90126648 0.97620055 0.51785966 0.65590088 0.64008421]
 [1.         0.4082438  0.61172946 0.84637731 0.12702347]]
[[0.75182978 0.47522328 0.84233197 0.97246107 0.80986122]
 [0.95889772 0.0411277  0.83702972 0.52276035 0.00179819]
 [0.81156464 0.74908538 0.         0.84642313 0.63349342]
 [0.90085799 0.97610209 0.51586494 0.65447726 0.63859515]
 [1.         0.40579557 0.6101231  0.84574174 0.12341177]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [113]:
rgba = np.dtype([('r', np.uint8), ('g', np.uint8), ('b', np.uint8), ('a', np.uint8)])

picture = np.zeros((5,5), dtype=rgba)
picture[0,0] = (255,255,255,255)
picture

array([[(255, 255, 255, 255), (  0,   0,   0,   0), (  0,   0,   0,   0),
        (  0,   0,   0,   0), (  0,   0,   0,   0)],
       [(  0,   0,   0,   0), (  0,   0,   0,   0), (  0,   0,   0,   0),
        (  0,   0,   0,   0), (  0,   0,   0,   0)],
       [(  0,   0,   0,   0), (  0,   0,   0,   0), (  0,   0,   0,   0),
        (  0,   0,   0,   0), (  0,   0,   0,   0)],
       [(  0,   0,   0,   0), (  0,   0,   0,   0), (  0,   0,   0,   0),
        (  0,   0,   0,   0), (  0,   0,   0,   0)],
       [(  0,   0,   0,   0), (  0,   0,   0,   0), (  0,   0,   0,   0),
        (  0,   0,   0,   0), (  0,   0,   0,   0)]],
      dtype=[('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')])

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [115]:
foo = np.zeros((5,3))
bar = np.ones((3,2))
foo @ bar

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [127]:
ary = np.array([1,5,2,6,8,4,3,5,7,7,4,4,6,7,4,1,1,7,9,6,4])

# this works but is not in-place
np.where((ary >= 3) & (ary <= 8), -ary, ary)

ary[(ary >= 3) & (ary <= 8)] *= -1
print(ary)


[ 1 -5  2 -6 -8 -4 -3 -5 -7 -7 -4 -4 -6 -7 -4  1  1 -7  9 -6 -4]


#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [131]:
print(sum(range(5),-1)) # 9
print(np.sum(range(5),-1)) # 10

9
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [143]:
Z = np.array([1,2,3,4])
print(Z**Z)
print(2 << Z >> 2)
print(Z < -Z)
print(1j*Z)
print(Z/1/1)
# print(Z<Z>) - invalid

[  1   4  27 256]
[1 2 4 8]
[False False False False]
[0.+1.j 0.+2.j 0.+3.j 0.+4.j]
[1. 2. 3. 4.]


#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [149]:
print(np.array(0))
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

0
nan
0
[0.]


/tmp/ipykernel_6656/4241516590.py:2: RuntimeWarning: invalid value encountered in divide
  print(np.array(0) / np.array(0))
/tmp/ipykernel_6656/4241516590.py:3: RuntimeWarning: divide by zero encountered in floor_divide
  print(np.array(0) // np.array(0))
/tmp/ipykernel_6656/4241516590.py:4: RuntimeWarning: invalid value encountered in cast
  print(np.array([np.nan]).astype(int).astype(float))


#### 29. How to round away from zero a float array ? (★☆☆)

In [159]:
foo = np.array([1.2, -3.2, 4.6, -10.2])

print(np.where(foo < 0, -(np.ceil(-foo)), np.ceil(foo)))
print(np.sign(foo) * np.ceil(np.abs(foo)))

[  2.  -4.   5. -11.]
[  2.  -4.   5. -11.]


#### 30. How to find common values between two arrays? (★☆☆)

In [164]:
a1 = np.array([[1,2],[3,4],[4,5]])
a2 = np.array([1, 7, 4, 5, 6])

print(np.unique(a1))
print(np.unique(a2))

print(np.intersect1d(a1, a2))

[1 2 3 4 5]
[1 4 5 6 7]
[1 4 5]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [168]:
# First throws an exception because np.sqrt() won't go into "complex mode" when given an integer argument
# Second returns 1j because `emath` has "automatic domain" - it knows how to "do the right thing"

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [177]:
import datetime as dt

today = dt.date.today()
oneday = dt.timedelta(days =1)
yesterday = today - oneday
tomorrow = today + oneday
print(yesterday, today, tomorrow)

2025-11-20 2025-11-21 2025-11-22


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [209]:
# attempt 1 - clobbers A

A = np.array([[1.,2.], [3.,4.]])
B = np.array([[5.,6.], [6.,7.]])

Out = np.copy(A)
Out += B
A *= -0.5
Out *= A

print(Out)

# attempt 2 - rearrange formula and we can avoid clobbering A

A = np.array([[1.,2.], [3.,4.]])
B = np.array([[5.,6.], [6.,7.]])

Out = np.copy(A)
Out += B
Out *= -0.5
Out *= A
print(Out)

# attempt 3 - if we're ok with clobbering, we can do it without an Out variable
# and use B as the destination. this only works because B is only referenced once!

A = np.array([[1.,2.], [3.,4.]])
B = np.array([[5.,6.], [6.,7.]])

B += A
B *= -0.5
B *= A
print(B)

[[ -3.   -8. ]
 [-13.5 -22. ]]
[[ -3.   -8. ]
 [-13.5 -22. ]]
[[ -3.   -8. ]
 [-13.5 -22. ]]


#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

#### 40. Create a random vector of size 10 and sort it (★★☆)

#### 41. How to sum a small array faster than np.sum? (★★☆)

#### 42. Consider two random arrays A and B, check if they are equal (★★☆)

#### 43. Make an array immutable (read-only) (★★☆)

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

#### 48. Print the minimum and maximum representable values for each numpy scalar type (★★☆)

#### 49. How to print all the values of an array? (★★☆)

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

#### 53. How to convert a float (32 bits) array into an integer (32 bits) array in place?

#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

#### 56. Generate a generic 2D Gaussian-like array (★★☆)

#### 57. How to randomly place p elements in a 2D array? (★★☆)

#### 58. Subtract the mean of each row of a matrix (★★☆)

#### 59. How to sort an array by the nth column? (★★☆)

#### 60. How to tell if a given 2D array has null columns? (★★☆)

#### 61. Find the nearest value from a given value in an array (★★☆)

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

#### 63. Create an array class that has a name attribute (★★☆)

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

#### 69. How to get the diagonal of a dot product? (★★★)

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

#### 71. Consider an array of dimension (5,5,3), how to multiply it by an array with dimensions (5,5)? (★★★)

#### 72. How to swap two rows of an array? (★★★)

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

#### 75. How to compute averages using a sliding window over an array? (★★★)

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

#### 80. Consider an arbitrary array, write a function that extracts a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

#### 82. Compute a matrix rank (★★★)

#### 83. How to find the most frequent value in an array?

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

#### 86. Consider a set of p matrices with shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combination of every item) (★★★)

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

In [197]:
# all pretty much the same
Z = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(Z*Z*Z)
print(Z**3)
print(np.power(Z,3))

# in-place
Z = np.array([[1,2,3],[4,5,6],[7,8,9]])
np.power(Z,3,out=Z)
print(Z)

# in-place
Z = np.array([[1,2,3],[4,5,6],[7,8,9]])
Z **= 3
print(Z)

# ChatGPT came up with this one... bizarre approach
Z = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(np.multiply.reduce(np.stack([Z,Z,Z]), axis=0))

# Again, ChatGPT - no idea why this is/could be better
import numexpr
numexpr.evaluate("Z*Z*Z")

[[  1   8  27]
 [ 64 125 216]
 [343 512 729]]
[[  1   8  27]
 [ 64 125 216]
 [343 512 729]]
[[  1   8  27]
 [ 64 125 216]
 [343 512 729]]
[[  1   8  27]
 [ 64 125 216]
 [343 512 729]]
[[  1   8  27]
 [ 64 125 216]
 [343 512 729]]
[[  1   8  27]
 [ 64 125 216]
 [343 512 729]]


array([[  1,   8,  27],
       [ 64, 125, 216],
       [343, 512, 729]], dtype=int64)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)