In [27]:
import numpy as np

In [7]:
a = np.arange(15).reshape(3, 5)

In [9]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [11]:
a.ndim

2

In [13]:
a.shape

(3, 5)

In [15]:
a.size

15

In [17]:
a.dtype

dtype('int64')

In [19]:
a.itemsize

8

In [21]:
a.data

In [23]:
type(a)

numpy.ndarray

In [25]:
b = np.array([[1,2], [3,4], [5,6]])

In [26]:
b

array([[1, 2],
       [3, 4],
       [5, 6]])

In [29]:
c = np.array([[1,2], [3,4]], dtype=complex)

In [30]:
c

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j]])

In [33]:
np.zeros((2, 4), dtype=np.int16)

array([[0, 0, 0, 0],
       [0, 0, 0, 0]], dtype=int16)

In [34]:
np.empty((2,2))

array([[0., 0.],
       [0., 0.]])

In [36]:
d = np.array([[1,2],[3,4]])
e = np.array([[5,6],[7,8]])

In [38]:
d + e

array([[ 6,  8],
       [10, 12]])

In [40]:
d * 2

array([[2, 4],
       [6, 8]])

In [41]:
d * e

array([[ 5, 12],
       [21, 32]])

In [43]:
d + 10

array([[11, 12],
       [13, 14]])

In [44]:
np.linspace(0, 2*np.pi, 100)

array([0.        , 0.06346652, 0.12693304, 0.19039955, 0.25386607,
       0.31733259, 0.38079911, 0.44426563, 0.50773215, 0.57119866,
       0.63466518, 0.6981317 , 0.76159822, 0.82506474, 0.88853126,
       0.95199777, 1.01546429, 1.07893081, 1.14239733, 1.20586385,
       1.26933037, 1.33279688, 1.3962634 , 1.45972992, 1.52319644,
       1.58666296, 1.65012947, 1.71359599, 1.77706251, 1.84052903,
       1.90399555, 1.96746207, 2.03092858, 2.0943951 , 2.15786162,
       2.22132814, 2.28479466, 2.34826118, 2.41172769, 2.47519421,
       2.53866073, 2.60212725, 2.66559377, 2.72906028, 2.7925268 ,
       2.85599332, 2.91945984, 2.98292636, 3.04639288, 3.10985939,
       3.17332591, 3.23679243, 3.30025895, 3.36372547, 3.42719199,
       3.4906585 , 3.55412502, 3.61759154, 3.68105806, 3.74452458,
       3.8079911 , 3.87145761, 3.93492413, 3.99839065, 4.06185717,
       4.12532369, 4.1887902 , 4.25225672, 4.31572324, 4.37918976,
       4.44265628, 4.5061228 , 4.56958931, 4.63305583, 4.69652

Arithmetic operators apply __elementwise__:

In [46]:
a = np.array([1, 2, 3, 4])

In [48]:
b = np.arange(4)

In [49]:
print(a)

[1 2 3 4]


In [50]:
print(b)

[0 1 2 3]


In [51]:
a + b

array([1, 3, 5, 7])

In [52]:
a - b

array([1, 1, 1, 1])

In [53]:
a ** 2

array([ 1,  4,  9, 16])

In [54]:
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [55]:
10 * np.sin(a)

array([ 8.41470985,  9.09297427,  1.41120008, -7.56802495])

Comparison operators work too!

In [56]:
a < 2

array([ True, False, False, False])

In [57]:
a < 3

array([ True,  True, False, False])

The product operator `*` works elementwise too; use the matrix product operator `@` or `dot` function...

In [60]:
l = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
r = np.array([[2, 2, 2], [3, 3, 3], [4, 4, 4]])

In [61]:
l * r

array([[ 2,  4,  6],
       [12, 15, 18],
       [28, 32, 36]])

In [62]:
l @ r

array([[20, 20, 20],
       [47, 47, 47],
       [74, 74, 74]])

In [63]:
l.dot(r)

array([[20, 20, 20],
       [47, 47, 47],
       [74, 74, 74]])

In [64]:
(l @ r) == (l.dot(r))

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

You can use operators like `+=` and `*=` to update arrays in place

In [66]:
a = np.array([[1, 2], [3, 4]])

In [67]:
a += 1

In [68]:
print(a)

[[2 3]
 [4 5]]


In [69]:
a *= 10

In [70]:
print(a)

[[20 30]
 [40 50]]


# Upcasting

In [71]:
a = np.ones(3, dtype=np.int32)
b = np.linspace(0, np.pi, 3)

In [72]:
b.dtype.name

'float64'

In [73]:
(a + b).dtype.name

'float64'

In [74]:
print(a + b)

[1.         2.57079633 4.14159265]


In [75]:
np.exp((a+b) * 1j).dtype.name

'complex128'

# Unary Operations
By default these apply to multi-dimensional arrays as though they were a list of numbers (shape is ignored)

In [76]:
a = np.array([[1,2,3], [4,5,6]])

In [77]:
a.sum()

21

In [78]:
a.min()

1

In [79]:
a.max()

6

Use the `axis` parameter to select an axis:

In [80]:
a.sum(axis=1)

array([ 6, 15])

In [82]:
a.sum(axis=0)

array([5, 7, 9])

In [83]:
a.cumsum(axis=1) # cumulative sum along each row

array([[ 1,  3,  6],
       [ 4,  9, 15]])

In [84]:
a.cumsum(axis=0)

array([[1, 2, 3],
       [5, 7, 9]])

# Universal Functions

`exp`, `sqrt`, `add`... and lots more

From the quickstart guide:

```
all, any, apply_along_axis, argmax, argmin, argsort, average, bincount, ceil, clip, conj, corrcoef, cov, cross, cumprod, cumsum, diff, dot, floor, inner, invert, lexsort, max, maximum, mean, median, min, minimum, nonzero, outer, prod, re, round, sort, std, sum, trace, transpose, var, vdot, vectorize, where
```

In [85]:
a = np.array([[1, 2], [3, 4]])

In [87]:
np.exp(a)

array([[ 2.71828183,  7.3890561 ],
       [20.08553692, 54.59815003]])

In [88]:
np.sqrt(a)

array([[1.        , 1.41421356],
       [1.73205081, 2.        ]])

In [89]:
np.add(a, a)

array([[2, 4],
       [6, 8]])

In [90]:
np.mean(a)

2.5

In [91]:
np.invert(a)

array([[-2, -3],
       [-4, -5]])

In [92]:
np.transpose(a)

array([[1, 3],
       [2, 4]])

# Indexing, slicing, and iterating

In [94]:
a = np.arange(10)**3

In [95]:
a

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729])

In [96]:
a[2]

8

In [97]:
a[2:5]

array([ 8, 27, 64])

In [98]:
a[1] = 10
a

array([  0,  10,   8,  27,  64, 125, 216, 343, 512, 729])

In [99]:
a[:6:2] = 1000

In [100]:
a

array([1000,   10, 1000,   27, 1000,  125,  216,  343,  512,  729])

In [101]:
a[::-1]

array([ 729,  512,  343,  216,  125, 1000,   27, 1000,   10, 1000])

In [103]:
for i in a:
    print(i)

1000
10
1000
27
1000
125
216
343
512
729


In [107]:
def f(row, col):
    return 10 * row + col
b = np.fromfunction(f, (5, 4), dtype=np.int32)

In [108]:
b

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13],
       [20, 21, 22, 23],
       [30, 31, 32, 33],
       [40, 41, 42, 43]], dtype=int32)

In [109]:
b[0]

array([0, 1, 2, 3], dtype=int32)

In [110]:
b[1]

array([10, 11, 12, 13], dtype=int32)

In [111]:
b[1][1]

11

In [112]:
b[2, 3]

23

In [113]:
b[0:5]

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13],
       [20, 21, 22, 23],
       [30, 31, 32, 33],
       [40, 41, 42, 43]], dtype=int32)

In [114]:
b[0:5, 1]

array([ 1, 11, 21, 31, 41], dtype=int32)

In [115]:
b[0:5, 2]

array([ 2, 12, 22, 32, 42], dtype=int32)

In [116]:
b[0:5, 1:3]

array([[ 1,  2],
       [11, 12],
       [21, 22],
       [31, 32],
       [41, 42]], dtype=int32)

In [117]:
b[2:4, 1:3]

array([[21, 22],
       [31, 32]], dtype=int32)

In [118]:
b[0:5, 1:2]

array([[ 1],
       [11],
       [21],
       [31],
       [41]], dtype=int32)

In [119]:
b[:, 1:2]

array([[ 1],
       [11],
       [21],
       [31],
       [41]], dtype=int32)

In [120]:
b[:,:]

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13],
       [20, 21, 22, 23],
       [30, 31, 32, 33],
       [40, 41, 42, 43]], dtype=int32)

In [121]:
b[1:3, :]

array([[10, 11, 12, 13],
       [20, 21, 22, 23]], dtype=int32)

In [122]:
b[-1]

array([40, 41, 42, 43], dtype=int32)

In [123]:
b[-1, :]

array([40, 41, 42, 43], dtype=int32)

In [124]:
b[:]

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13],
       [20, 21, 22, 23],
       [30, 31, 32, 33],
       [40, 41, 42, 43]], dtype=int32)

In [125]:
b[0]

array([0, 1, 2, 3], dtype=int32)

In [126]:
b[:,0]

array([ 0, 10, 20, 30, 40], dtype=int32)

In [127]:
b[1:3]

array([[10, 11, 12, 13],
       [20, 21, 22, 23]], dtype=int32)

In [128]:
b[1]

array([10, 11, 12, 13], dtype=int32)

In [129]:
b[:,1]

array([ 1, 11, 21, 31, 41], dtype=int32)

In [130]:
b[:,1:2]

array([[ 1],
       [11],
       [21],
       [31],
       [41]], dtype=int32)

## Indexing Rules of Thumb

When you index a single axis with a single integer, NumPy removes that axis from the result.

  - Any axis indexed with a scalar disappears.
  - Any axis indexed with a slice, list, or array stays.

In [131]:
b[:,1]

array([ 1, 11, 21, 31, 41], dtype=int32)

In [132]:
b[:,1:2]

array([[ 1],
       [11],
       [21],
       [31],
       [41]], dtype=int32)

# Shape Manipulation

In [134]:
a = np.array([[3, 7, 3, 4], [1, 4, 2, 2], [7, 2, 4, 9]])

In [135]:
a

array([[3, 7, 3, 4],
       [1, 4, 2, 2],
       [7, 2, 4, 9]])

In [136]:
a.shape

(3, 4)

In [138]:
a.ravel() # flatten

array([3, 7, 3, 4, 1, 4, 2, 2, 7, 2, 4, 9])

In [139]:
a.reshape(6, 2) # modify the shape

array([[3, 7],
       [3, 4],
       [1, 4],
       [2, 2],
       [7, 2],
       [4, 9]])

In [140]:
a.reshape(100, 2)

ValueError: cannot reshape array of size 12 into shape (100,2)

In [141]:
a.reshape(2, 2)

ValueError: cannot reshape array of size 12 into shape (2,2)

In [143]:
a.T # transpose

array([[3, 1, 7],
       [7, 4, 2],
       [3, 2, 4],
       [4, 2, 9]])

In [144]:
a

array([[3, 7, 3, 4],
       [1, 4, 2, 2],
       [7, 2, 4, 9]])

In [145]:
a.shape

(3, 4)

In [146]:
a.T.shape

(4, 3)

In [147]:
b = np.array([[3, 7, 3, 4], [1, 4, 2, 2], [7, 2, 4, 9]])

In [150]:
b.resize((2, 6)) # this operates in-place

In [149]:
b

array([[3, 7, 3, 4, 1, 4],
       [2, 2, 7, 2, 4, 9]])

In [151]:
c = np.array([[1, 2], [3, 4]])
d = np.array([[5, 6], [7, 8]])

In [153]:
np.vstack((c, d))

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [154]:
np.hstack((c, d))

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])