In [2]:
import numpy as np

## `np.diag()`

In [3]:
np.diag([1,2,3])

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [7]:
np.diag([1,2,3], k=1) # k - the diagonal. 0 = main diagonal, k>0 for diagonals ABOVE the main

array([[0, 1, 0, 0],
       [0, 0, 2, 0],
       [0, 0, 0, 3],
       [0, 0, 0, 0]])

In [5]:
np.diag([1,2,3], k=3)

array([[0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 2, 0],
       [0, 0, 0, 0, 0, 3],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

In [8]:
np.diag([1,2,3], k=-1) # and uses k<0 for diagonals BELOW the main

array([[0, 0, 0, 0],
       [1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0]])

## `np.indices()`

In [11]:
ind = np.indices((8,8))

In [12]:
print(ind.shape)

(2, 8, 8)


In [13]:
print(ind)

[[[0 0 0 0 0 0 0 0]
  [1 1 1 1 1 1 1 1]
  [2 2 2 2 2 2 2 2]
  [3 3 3 3 3 3 3 3]
  [4 4 4 4 4 4 4 4]
  [5 5 5 5 5 5 5 5]
  [6 6 6 6 6 6 6 6]
  [7 7 7 7 7 7 7 7]]

 [[0 1 2 3 4 5 6 7]
  [0 1 2 3 4 5 6 7]
  [0 1 2 3 4 5 6 7]
  [0 1 2 3 4 5 6 7]
  [0 1 2 3 4 5 6 7]
  [0 1 2 3 4 5 6 7]
  [0 1 2 3 4 5 6 7]
  [0 1 2 3 4 5 6 7]]]


In [14]:
parity = ind & 1

In [15]:
print(parity)

[[[0 0 0 0 0 0 0 0]
  [1 1 1 1 1 1 1 1]
  [0 0 0 0 0 0 0 0]
  [1 1 1 1 1 1 1 1]
  [0 0 0 0 0 0 0 0]
  [1 1 1 1 1 1 1 1]
  [0 0 0 0 0 0 0 0]
  [1 1 1 1 1 1 1 1]]

 [[0 1 0 1 0 1 0 1]
  [0 1 0 1 0 1 0 1]
  [0 1 0 1 0 1 0 1]
  [0 1 0 1 0 1 0 1]
  [0 1 0 1 0 1 0 1]
  [0 1 0 1 0 1 0 1]
  [0 1 0 1 0 1 0 1]
  [0 1 0 1 0 1 0 1]]]


In [16]:
parity.shape

(2, 8, 8)

In [19]:
parity.sum(axis=0) # collapse axis 0 by summing along it

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 2, 1, 2, 1, 2, 1, 2],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 2, 1, 2, 1, 2, 1, 2],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 2, 1, 2, 1, 2, 1, 2],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 2, 1, 2, 1, 2, 1, 2]])

In [18]:
parity[0] + parity[1]

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 2, 1, 2, 1, 2, 1, 2],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 2, 1, 2, 1, 2, 1, 2],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 2, 1, 2, 1, 2, 1, 2],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 2, 1, 2, 1, 2, 1, 2]])