In [1]:
import numpy as np

In [2]:
import matplotlib.pyplot as plt

In [25]:
from ipywidgets import interact, FloatSlider

In [50]:
def softmax(x, T=1.0):
    # scale by inverse of temperature
    # linear relationship remains the same but magnitude changes
    # > 1 - reduces the spread of values
    # = 1 - spread unchange
    # < 1 - increases the spread
    x = x * (1 / T)

    # this step is because we're running on a computer with limited precision
    # e.g. if x.max() was 1000, exp(1000) is infinity, and this will poison the
    # calculations. subtracting the maximum means the max value is always 0, and
    # exp(0) is 1. exp() of a negative number will always yield a value between 0...1
    #
    # proof that this doesn't change the result:
    # 
    # let c = x.max()
    # e^(x-c) = e^(-c) . e^(x)          [standard law of indexes]
    #
    #    (e^(-c) . e^(x)) / sum(e^(-c) . e^(x_j))
    # => (e^(-c) . e^(x)) / e^(-c) . sum(e^(x_j))
    # => e^(x) / sum(e^(x_j))
    #
    # The e^(x-c) term cancels out!
    x = x - x.max()

    # e^x
    e = np.exp(x)

    # normalise so that all values sum to 1
    return e / e.sum()

In [51]:
logits = np.array([2.0, 1.0, 0.1, -0.5, 4.0, 5.0])
temps = [0.5, 1.0, 2.0, 5.0]

In [52]:
def plot_softmax(T=1.0):
    probs = softmax(logits, T)
    x = np.arange(len(logits))
    fig, ax = plt.subplots()
    ax.bar(x, probs)
    ax.set_xticks(x)
    ax.set_xticklabels([f'logit {j}' for j in range(len(logits))])
    ax.set_ylim(0, 1)                    # fix the axis so bars don't rescale
    ax.set_ylabel('probability')
    ax.set_title(f'Softmax at T={T:.2f}')
    plt.show()

In [53]:
interact(plot_softmax, T=FloatSlider(min=0.1, max=10.0, step=0.1, value=1.0))

interactive(children=(FloatSlider(value=1.0, description='T', max=10.0, min=0.1), Output()), _dom_classes=('wi…

<function __main__.plot_softmax(T=1.0)>

In [54]:
foo = np.array([1,2,3,4,5,10,15,20])

In [55]:
foo / 1

array([ 1.,  2.,  3.,  4.,  5., 10., 15., 20.])

In [56]:
foo / 100

array([0.01, 0.02, 0.03, 0.04, 0.05, 0.1 , 0.15, 0.2 ])

In [57]:
foo / 0.1

array([ 10.,  20.,  30.,  40.,  50., 100., 150., 200.])